### ISSUE TITLE
"No insertion burn" tickbox

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [Krafpy/KSP-MGA-Planner#17]
same idea as [Alexmoon's Launch Window Planner](https://alexmoon.github.io/ksp/):
![image](https://user-images.githubusercontent.com/14184826/185479707-e4521d23-a37c-4b88-8c3b-e1771507eed4.png)

**Comment by nmisyats** [comment]
Hello ! I added it just now. Do not hesitate to open a new issue if you encouter any problem.
