### ISSUE TITLE
suggestion: include a button to more easily copy the results

### ISSUE THREAD

**Issue by LaBalladeDesCieux** [Krafpy/KSP-MGA-Planner#29]
Once the tools is done calculating and gives the results, I think it'd be great if users could have an arena where the results could be easily copy-pasted into a .txt file. 

Context: I have been using your (great!) tool to plan a Jool-5 mission and I often want to compare two and more gravity assists sequences to see which one is the less costly in terms of d/V. However, every time I input a new trajectory the precedent results fade away, which isn't convenient to compare two gravity assists sequences. Another reason as why I'd like to save the results in some way is to save the departure date which might useful to have a rough date when to do the sequence.

The textdrop should include the details for every maneuver the gravity assist sequence include, so users can save it into some .txt file to later use.

Note: I don't have a KSP forum account but have a Github account, hence why I write here.
Thanks for the tool, thanks for reading, and happy new year :eyes:

**Comment by nmisyats** [comment]
Hello ! Thank you for your suggestion, I agree it would be useful !
I can add a button that directly downloads a txt file with the details of the trajectory, or is a text area where to copy the text from necessary ?
The first solution is easier to implement and integrate in the existing tool, and I think a text pannel isn't very useful if it's just to copy past it into a text file immediatly.

Happy new year !

**Comment by LaBalladeDesCieux** [comment]
I was thinking that users might not always want to download a file (e.g if they're scared of virus somehow) but for me a download would work yeah!

**Comment by nmisyats** [comment]
Alright, I'll add that as soon as I can.

**Comment by nmisyats** [comment]
Here is what the text version would look like (example of a Kerbin - Eve - Moho mission):
```
Sequence:               Kerbin-Eve-Moho
Departure:              Year 18 - Day 202 - 01:53:51
Arrival:                Year 19 - Day 86 - 01:42:34
Total ΔV:               2697.1 m/s

Steps:

  Kerbin escape:
    Date:               T+ 0y - 0d - 00:00:00 MET
    Ejection angle:     55.8°
    ΔV:                 1183.7 m/s
      Prograde:         1183.7
      Normal:           0.0
      Radial:           -0.0

  Kerbin-Eve DSM:
    Date:               T+ 0y - 14d - 02:12:22 MET
    ΔV:                 295.8 m/s
      Prograde:         -112.2
      Normal:           277.4
      Radial:           -2.1

  Flyby around Eve:
    SOI enter date:     T+ 0y - 204d - 04:13:32 MET
    SOI exit date:      T+ 0y - 207d - 00:56:52 MET
    Periapsis altitude: 311 km
    Inclination:        22°

  Eve-Moho DSM:
    Date:               T+ 0y - 208d - 01:11:58 MET
    ΔV:                 0.0 m/s
      Prograde:         -0.0
      Normal:           0.0
      Radial:           0.0

  Moho circularization:
    Date:               T+ 0y - 309d - 05:48:42 MET
    ΔV:                 1214.1 m/s
      Prograde:         -1214.1
      Normal:           -0.0
      Radial:           0.0
```

Is there missing information I should add ?

**Comment by LaBalladeDesCieux** [comment]
Ideally, I think that the date in Universal Time should be slashed along Mission Elapsed Time in the whole tool, as it is not possible for the mission to start on the LKO burn. However, given times with this tool are imprecise anyway (and it's a a whole another suggestion) it should be fine. Everything else is fine too!

**Comment by nmisyats** [comment]
I made a draggable text box with the trajectory details in it. I also added the UT time for maneuvers (in the detailed text). I still have some things to fix but I should be able to finish this feature by the end of the day.

<img width="555" alt="Screenshot_20230102_170117" src="https://user-images.githubusercontent.com/68777856/210255376-9409a59f-fd92-4f10-bbf4-5f4c95c4554e.png">

**Comment by nmisyats** [comment]
I added the feature in the `trajectory-to-text` branch. If you know how to run the tool locally you can try it out. I'll merge it soon unless there is something I need to change/add ?
